name: codemagic_manager
description: Package allowing to query Codemagic builds and applications from the recently exposed API
version: 0.1.2+1
homepage: https://roszkowski.dev
issue_tracker: https://github.com/orestesgaolin/codemagic_manager/issues
repository: https://github.com/orestesgaolin/codemagic_manager
documentation: https://pub.dev/documentation/codemagic_manager/latest/

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^3.0.9
  freezed_annotation: ^0.7.1
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  freezed: ^0.10.9
  json_serializable: ^3.3.0

flutter:
