name: example
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  codemagic_manager:
    path: ../

  cupertino_icons: ^0.1.3

dev_dependencies:

flutter:
  uses-material-design: true
